#!/bin/bash

bspc config window_gap 0           

if [[ $(cat ~/.config/polybar/polybar_shown) == "0" ]]
then
	bspc config top_padding 0
	bspc config bottom_padding 0
	bspc config left_padding 0
	bspc config right_padding 0
	exit 0
fi

bspc config top_padding 30
bspc config bottom_padding 30
bspc config left_padding 0
bspc config right_padding 0


