#!/bin/bash

ID=$(xinput --list | grep "$1" | cut -d '=' -f 2 | cut -d [ -f 1)

PROP=$(xinput --list-props $ID | grep "$2" | head -n 1 | cut -d '(' -f 2 | cut -d ')' -f 1)

xinput --set-prop $ID $PROP "$3"
