#!/bin/bash
#polybar -r top-left & disown
#polybar top-mid & disown
#polybar top-right & disown

#polybar bottom-left & disown
#polybar bottom-mid & disown
#polybar bottom-right & disown
# polybar system & disown
# wal --backend colortheif -q -i ~/.config/system/wallpaper.png

polybar bot & disown
polybar top & disown
sleep 0.5
bspsize

# ~/.local/src/eww/target/release/eww open topbar
# ~/.local/src/eww/target/release/eww open leftbar
