#!/bin/bash

cd ~/.local/src/NativeApps

nativefier --name "$1" \
--platform linux --arch x64 \
--width 1920 --height 1080 \
--tray --disable-dev-tools \
--single-instance "$2"

echo "#!/bin/bash\n~/.local/src/NativeApps/$1-linux-x64/$1" > "~/.local/bin/$1"

chmod +x "~/.local/bin/$1"
