#!/bin/bash

if [[ $1 == "" ]]
then
	echo "Error: No path specified..."
	exit 0
elif ! [[ $1 == *"/"* ]]
then
	echo "Error: invalid path..."
	exit 0
fi

if [[ @2 == "" ]]
then
	echo "Error: missing index"
	exit 0
fi

IFS='/' read -ra elements <<< "$1"

echo ${elements[$2]} 


