#!/bin/python

import random
import string
import sys
length = int(sys.argv[1])
chars = string.ascii_letters + string.digits + string.punctuation

pwd = ""

for i in range(length): 
	pwd+=chars[random.randint(1, len(chars)-1)]

print(pwd)
