#!/bin/bash

if [[ $1 == "-n" ]]; then
	
	i=$(expr $(bspc query -T -d focused | jshon -e name -u) + 1)
fi

if [[ $1 == "-p" ]]; then
	i=$(expr $(bspc query -T -d focused | jshon -e name -u) - 1)
fi

bspc desktop -f ^$i
