#!/bin/bash

nid=$(cat ~/.config/system/wa-scp-id)

if [[ $(toggle-state ~/.config/system/wa-scp-shown) == "1" ]]
then
	bspc node $nid --flag hidden=off
	xdo activate $nid
	exit 0
fi

bspc node $nid --flag hidden=on
exit 0

